service: multi-platform-chatbot2

provider:
  name: aws
  runtime: python3.7
  region: us-east-2
  stackName: multi-platform-chatbot2
  apiName: multi-platform-chatbot2

layers:
  crawler:
    name: Crawler
    path: ./lambda_layers

functions:
  slack_handler:
    handler: api.slack.handler
    name: handler-slack
    description: Slack command handler
    memorySize: 128
    events:
      - http:
          path: /slack
          method: post
    layers:
      - {Ref: CrawlerLambdaLayer}
      
  slack_action:
    handler: api.slack_action.handler
    name: handler-slack-action
    description: Slack action handler
    memorySize: 128
    events:
      - http:
          path: /slack-action
          method: post
package:
  exclude:
    - node_modules/**
