service: multi-platform-chatbot

provider:
  name: aws
  runtime: python3.7
  region: us-east-2
  stackName: multi-platform-chatbot
  apiName: multi-platform-chatbot

layers:
  crawler:
    name: Crawler
    path: ./lambda_layers

functions:
  aws_news:
    handler: api.slack.handler
    name: handler-slack
    description: Slack command handler
    memorySize: 128
    events:
      - http:
          path: /slack
          method: post
    layers:
      - {Ref: CrawlerLambdaLayer}

package:
  exclude:
    - node_modules/**
